# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_dist <- function(X) {
    .Call(`_tutorial_arma_dist`, X)
}

demo_class <- function() {
    invisible(.Call(`_tutorial_demo_class`))
}

test <- function(seed, nn1, nn2, nn3) {
    invisible(.Call(`_tutorial_test`, seed, nn1, nn2, nn3))
}

